### ISSUE TITLE
Add system tray

### ISSUE THREAD

**Issue by kettek** [kettek/crummy-webm-capture#2]
See https://www.electronjs.org/docs/latest/api/tray

We should also make it so minimizing the window "hides it" to the tray.

**Comment by Vexmage** [comment]
Hmm what are we using for icons and such, do we need to create some, like for a tray icon in this instance?

**Comment by Vexmage** [comment]
I can do that pretty quick but I want to check to see if we have a certain style or branding already.

**Comment by kettek** [comment]
We ain't got nuffin'. Whatever it is should be relatively visually simple, possibly just something vector so we can just scale to whatever sizes are needed (I believe smallest is 16x16, with largest being like 64x64@2).

The system tray icon should have a "default" icon and a "recording" icon -- the latter could just be the former but with a red filled circle in some corner.

**Comment by kettek** [comment]
As far as menu entries, for now just a "show/hide", "stop" (if recording -- this will require some IPC), and "quit".  In the future might tie in functionality with last selected recording target for it to start.

**Comment by kettek** [comment]
Closed by PR #4
